# Site settings
# TODO: Add subtitle under 'Starchitect' title
title: Starchitect
# TODO: Replace with more convient 'anton@starchitect.info' or 'starchitect@starchitect.info'
email: anton@vorobyev.co
# TODO: Chech grammary and fill with more prosaic description
description: >
  Starchitect is all about and beyond software engineering and architecture.
# TODO: Clear using of post log, all log, etc
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://starchitect.info" # the base hostname & protocol for your site

# TODO: Review it and change with actual contacts
#twitter_username: jekyllrb
#github_username:  jekyll

timezone: Asia/Yekaterinburg

# Build settings
markdown: kramdown
